	program armar_coords_grom
	implicit none
	integer :: natom, i
	real*8, dimension(:,:), allocatable :: r
	integer, dimension(:), allocatable :: num
	character(len=5) :: jovobich
	character(len=4), dimension(:), allocatable :: resname
	character(len=2), dimension(:), allocatable :: typename
	real*8, dimension(9) :: box

	real*8 :: b_2_gro
	b_2_gro =1.d0
! 0.52917725D1
	natom = 3
	
         open(unit=50,file="em.gro")
	 read(50,*) jovobich
	 read(50,*) natom
	 allocate(resname(natom), typename(natom), num(natom), r(natom,3))

         DO i=1,NATOM
            read(50,*) resname(i),typename(i), num(i), r(i,1), r(i,2), r(i,3)
         END DO
	 read(50,*) (box(i),i=1,9)
	 close(50)

         open(unit=51,file="position-buffer2")
         DO i=1,NATOM
            read(51,*) r(i,1), r(i,2), r(i,3)
         END DO
	 close(51)

         open(unit=52,file="em.gro")
         write(52,*) jovobich
         write(52,*) natom
         DO i=1,NATOM
            write(52,4803) resname(i),typename(i), num(i),r(i,1)*b_2_gro, r(i,2)*b_2_gro, r(i,3)*b_2_gro
         END DO
	 write(52,4804) (box(i),i=1,9)
         close(52)
 4803   FORMAT(4x,A4,4x,A2,5x,i1,3x,3(f30.15,2x))
 4804   FORMAT(9(2x,f8.5))
	end program

!   6.48965   6.11850   5.29878   0.00000   0.00000  -2.16322   0.00000  -2.16322  -3.05925


!generated by VMD, t= 0.000000
!3
!    1WAT    O      1   3.273   3.602   3.032
!    1WAT    H1     2   3.205   3.612   3.098
!    1WAT    H2     3   3.355   3.607   3.081
!   6.48965   6.11850   5.29878   0.00000   0.00000  -2.16322   0.00000  -2.16322  -3.05925






